### PR TITLE
Allow cross-building

### PR DESCRIPTION
**Pull request by ndowens**
AC_RUN_* causes issues for cross-compiling
AC_COMPILE_IFELSE works fine with cross

### CODE REVIEW

**Comment by Edrusb** [comment]
Correct, I will review your proposal for possible side effects before merging it. Thanks for your feedback.

**Comment by ndowens** [comment]
> Correct, I will review your proposal for possible side effects before merging it. Thanks for your feedback.

https://github.com/void-linux/void-packages/pull/27557 if you like to see that it built successfully and for *-musl, *-glibc x86_64,i686,armv6,armv7 and aarch64

**Comment by Edrusb** [comment]
AC_RUN_IFELSE is not only used to check the binary runs in addition to the fact it can compile, to also executes some run-time testings which result is used to decide whether to active or not a feature:
- statx() may be present and usable but if it returns an error it will not be used
- ZSTD_version_Number() may be present, but if the version number that it returns is lower than the one supported by libdar zstd feature will not be activated
- similar thing for LZ4
- similar thing with libcrypt

replacing it by AC_RUN_IFELSE (or better AC_LINK_IFELSE) is not the best solution.
AC_RUN_IFELSE has a third argument to handle cross-compilation, I will use that instead

Cheers,
Denis

**Comment by ndowens** [comment]
Thank you for providing an alternative way to cross-build.

**Comment by Edrusb** [comment]
Can you double check that the current master code compiles also for you in cross-building context? Thanks

**Comment by ndowens** [comment]
> Can you double check that the current master code compiles also for you in cross-building context? Thanks

Tested and works with cross-compiling

**Comment by Edrusb** [comment]
OK, thanks for feedback, closing case

**Pull request closed without merging**
