### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Review by Edrusb — CHANGES_REQUESTED** [review]
Thanks! I don't see any modification for the second change (line 283) did I missed something?

**Comment by bryant1410** [comment]
I think GitHub automatically changed the line ending from \r\n to \n (I used GitHub to edit the file).

**Comment by bryant1410** [comment]
Oh, no, it's something about a "ö" char: https://patch-diff.githubusercontent.com/raw/Edrusb/DAR/pull/33.diff

**Comment by Edrusb** [comment]
OK, thanks for feedback!

**Pull request merged**
